version: "3.7"
services:
  db:
    image: "postgres:latest"
    restart: always
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432"

  dev:
    build:
      context: .
    command:
      - "/bin/bash"
    working_dir: "/app"
    env_file:
      - .env
    volumes:
      - ".:/app"
    depends_on:
      - db
  # pgadmin4:
  #   image: dpage/pgadmin4
  #   restart: always
  #   env_file:
  #     - .env
